# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/steffnet/Schreibtisch/ABP/Vivado/HDMI/hdmi/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_102M_1/hdmi_rst_ps7_0_102M_1.xci
# IP: The module: 'hdmi_rst_ps7_0_102M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/steffnet/Schreibtisch/ABP/Vivado/HDMI/hdmi/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_102M_1/hdmi_rst_ps7_0_102M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_102M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/steffnet/Schreibtisch/ABP/Vivado/HDMI/hdmi/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_102M_1/hdmi_rst_ps7_0_102M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_102M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/steffnet/Schreibtisch/ABP/Vivado/HDMI/hdmi/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_102M_1/hdmi_rst_ps7_0_102M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_102M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/steffnet/Schreibtisch/ABP/Vivado/HDMI/hdmi/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_102M_1/hdmi_rst_ps7_0_102M_1.xci
# IP: The module: 'hdmi_rst_ps7_0_102M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/steffnet/Schreibtisch/ABP/Vivado/HDMI/hdmi/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_102M_1/hdmi_rst_ps7_0_102M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_102M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/steffnet/Schreibtisch/ABP/Vivado/HDMI/hdmi/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_102M_1/hdmi_rst_ps7_0_102M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_102M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/steffnet/Schreibtisch/ABP/Vivado/HDMI/hdmi/hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_102M_1/hdmi_rst_ps7_0_102M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_102M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
