# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/hdmi/hdmi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi || ORIG_REF_NAME==hdmi} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_processing_system7_0_0/hdmi_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_processing_system7_0_0 || ORIG_REF_NAME==hdmi_processing_system7_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_iic_0_0/hdmi_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_iic_0_0 || ORIG_REF_NAME==hdmi_axi_iic_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_ps7_0_axi_periph_0/hdmi_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_ps7_0_axi_periph_0 || ORIG_REF_NAME==hdmi_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_rst_ps7_0_102M_0/hdmi_rst_ps7_0_102M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_rst_ps7_0_102M_0 || ORIG_REF_NAME==hdmi_rst_ps7_0_102M_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_auto_pc_0/hdmi_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_pc_0 || ORIG_REF_NAME==hdmi_auto_pc_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_sda_in_out_to_inout_0_1/hdmi_sda_in_out_to_inout_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_sda_in_out_to_inout_0_1 || ORIG_REF_NAME==hdmi_sda_in_out_to_inout_0_1} -quiet] -quiet

# XDC: bd/hdmi/ip/hdmi_processing_system7_0_0/hdmi_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_processing_system7_0_0 || ORIG_REF_NAME==hdmi_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/hdmi/ip/hdmi_axi_iic_0_0/hdmi_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_axi_iic_0_0 || ORIG_REF_NAME==hdmi_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi/ip/hdmi_axi_iic_0_0/hdmi_axi_iic_0_0_ooc.xdc

# XDC: bd/hdmi/ip/hdmi_rst_ps7_0_102M_0/hdmi_rst_ps7_0_102M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_rst_ps7_0_102M_0 || ORIG_REF_NAME==hdmi_rst_ps7_0_102M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi/ip/hdmi_rst_ps7_0_102M_0/hdmi_rst_ps7_0_102M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_rst_ps7_0_102M_0 || ORIG_REF_NAME==hdmi_rst_ps7_0_102M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi/ip/hdmi_auto_pc_0/hdmi_auto_pc_0_ooc.xdc

# XDC: bd/hdmi/hdmi_ooc.xdc
