# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/bd/fourier_bram/ip/fourier_bram_Freq2BRAM_1_0/fourier_bram_Freq2BRAM_1_0.xci
# IP: The module: 'fourier_bram_Freq2BRAM_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/ip/index_fifo/index_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==index_fifo || ORIG_REF_NAME==index_fifo} -quiet] -quiet

# IP: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/ip/data_fifo/data_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_fifo || ORIG_REF_NAME==data_fifo} -quiet] -quiet

# XDC: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/ip/index_fifo/index_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==index_fifo || ORIG_REF_NAME==index_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/ip/data_fifo/data_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==data_fifo || ORIG_REF_NAME==data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/bd/fourier_bram/ip/fourier_bram_Freq2BRAM_1_0/fourier_bram_Freq2BRAM_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fourier_bram_Freq2BRAM_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/bd/fourier_bram/ip/fourier_bram_Freq2BRAM_1_0/fourier_bram_Freq2BRAM_1_0.xci
# IP: The module: 'fourier_bram_Freq2BRAM_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/ip/index_fifo/index_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==index_fifo || ORIG_REF_NAME==index_fifo} -quiet] -quiet

# IP: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/ip/data_fifo/data_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_fifo || ORIG_REF_NAME==data_fifo} -quiet] -quiet

# XDC: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/ip/index_fifo/index_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==index_fifo || ORIG_REF_NAME==index_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/ip/data_fifo/data_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==data_fifo || ORIG_REF_NAME==data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/niklas/dev/uni/ABP/git/Vivado/FFT/FFT.srcs/sources_1/bd/fourier_bram/ip/fourier_bram_Freq2BRAM_1_0/fourier_bram_Freq2BRAM_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fourier_bram_Freq2BRAM_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
