set_property SRC_FILE_INFO {cfile:/home/steffnet/Schreibtisch/ABP/Vivado/HDMI/hdmi/hdmi.srcs/constrs_1/new/contraints.xdc rfile:../../../hdmi.srcs/constrs_1/new/contraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports IIC_0_sda_io]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA18 [get_ports IIC_0_scl_io]
