# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Uni/git/ABP/Vivado/FFT/FFT.srcs/sources_1/bd/fourier_bram/ip/fourier_bram_blkMemGenRight_0/fourier_bram_blkMemGenRight_0.xci
# IP: The module: 'fourier_bram_blkMemGenRight_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Uni/git/ABP/Vivado/FFT/FFT.srcs/sources_1/bd/fourier_bram/ip/fourier_bram_blkMemGenRight_0/fourier_bram_blkMemGenRight_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fourier_bram_blkMemGenRight_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Uni/git/ABP/Vivado/FFT/FFT.srcs/sources_1/bd/fourier_bram/ip/fourier_bram_blkMemGenRight_0/fourier_bram_blkMemGenRight_0.xci
# IP: The module: 'fourier_bram_blkMemGenRight_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Uni/git/ABP/Vivado/FFT/FFT.srcs/sources_1/bd/fourier_bram/ip/fourier_bram_blkMemGenRight_0/fourier_bram_blkMemGenRight_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fourier_bram_blkMemGenRight_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
